/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as ApiPublicTestShopifyWebhookRouteImport } from './routes/api/public/test-shopify-webhook'
import { Route as ApiPublicWebhooksShopifyOrdersCreateRouteImport } from './routes/api/public/webhooks/shopify.orders-create'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTestShopifyWebhookRoute =
  ApiPublicTestShopifyWebhookRouteImport.update({
    id: '/api/public/test-shopify-webhook',
    path: '/api/public/test-shopify-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksShopifyOrdersCreateRoute =
  ApiPublicWebhooksShopifyOrdersCreateRouteImport.update({
    id: '/api/public/webhooks/shopify/orders-create',
    path: '/api/public/webhooks/shopify/orders-create',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/customers': typeof CustomersRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/unlock': typeof UnlockRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/api/public/test-shopify-webhook': typeof ApiPublicTestShopifyWebhookRoute
  '/api/public/webhooks/shopify/orders-create': typeof ApiPublicWebhooksShopifyOrdersCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/customers': typeof CustomersRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/unlock': typeof UnlockRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/api/public/test-shopify-webhook': typeof ApiPublicTestShopifyWebhookRoute
  '/api/public/webhooks/shopify/orders-create': typeof ApiPublicWebhooksShopifyOrdersCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/customers': typeof CustomersRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/unlock': typeof UnlockRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/api/public/test-shopify-webhook': typeof ApiPublicTestShopifyWebhookRoute
  '/api/public/webhooks/shopify/orders-create': typeof ApiPublicWebhooksShopifyOrdersCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/customers'
    | '/settings'
    | '/templates'
    | '/unlock'
    | '/orders/$orderId'
    | '/api/public/test-shopify-webhook'
    | '/api/public/webhooks/shopify/orders-create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/customers'
    | '/settings'
    | '/templates'
    | '/unlock'
    | '/orders/$orderId'
    | '/api/public/test-shopify-webhook'
    | '/api/public/webhooks/shopify/orders-create'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/customers'
    | '/settings'
    | '/templates'
    | '/unlock'
    | '/orders/$orderId'
    | '/api/public/test-shopify-webhook'
    | '/api/public/webhooks/shopify/orders-create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CustomersRoute: typeof CustomersRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  UnlockRoute: typeof UnlockRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  ApiPublicTestShopifyWebhookRoute: typeof ApiPublicTestShopifyWebhookRoute
  ApiPublicWebhooksShopifyOrdersCreateRoute: typeof ApiPublicWebhooksShopifyOrdersCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/test-shopify-webhook': {
      id: '/api/public/test-shopify-webhook'
      path: '/api/public/test-shopify-webhook'
      fullPath: '/api/public/test-shopify-webhook'
      preLoaderRoute: typeof ApiPublicTestShopifyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/shopify/orders-create': {
      id: '/api/public/webhooks/shopify/orders-create'
      path: '/api/public/webhooks/shopify/orders-create'
      fullPath: '/api/public/webhooks/shopify/orders-create'
      preLoaderRoute: typeof ApiPublicWebhooksShopifyOrdersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CustomersRoute: CustomersRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  UnlockRoute: UnlockRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  ApiPublicTestShopifyWebhookRoute: ApiPublicTestShopifyWebhookRoute,
  ApiPublicWebhooksShopifyOrdersCreateRoute:
    ApiPublicWebhooksShopifyOrdersCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
